// Generated by CoffeeScript 2.7.0
(function() {
  var app;

  app = $.sammy('#main', function() {
    this.use(Sammy.Template, 'tpl');
    this.get('#/', function() {
      var user;
      this.swap('');
      /*user = {
        name: json[20].name,
        email: json[20].language,
        age: json[20].bio,
        ego: json[20].id,
        temper: json[20].version
      };
      
      //this.$element().append("<h1>" + user.name + "</h1>");
      //$("body").data('user', user);
      //$("body").html("");
      //$("body").append("<h1>" + user.name + "</h1>");
     
      return this.partial("user.tpl", {
        user: user
      });*/

      $.getJSON("https://luismgz.github.io/myjson.json", function(data){
        $("#main").append(JSON.stringify(data));
      });
      
    });
    
    this.get('#/london/', function() {
      var apiKey;
      this.swap('');
      //$("body").click -> alert JSON.stringify $(this).data 'user'
      apiKey = "4ea0589194d27ee4f46e3e5f56474ef5";
      return $.get(`https://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=${apiKey}`, (data) => {
        return this.partial('weather.tpl', {
          data: data
        });
      });
    });
    this.get('#/about/', function() {
      return this.load('about.html').swap();
    });
    this.get('#/contact/', function() {
      return this.load('contact.html').swap();
    });
    this.get('#/label/:name', function() {
      this.swap('');
      return this.$element().append(`<h1>${this.params['name']}</h1>`);
    });
    this.get('#/compose', function() {
      this.app.swap('');
      return this.$element().append('<h1>say hello to?</h1>' + '<form action="#/compose" method="post">' + '<input type="text" name="to" />' + '<input type="submit" name="submit" />' + '</form>');
    });
    return this.post('#/compose', function() {
      var to;
      this.app.swap('');
      to = this.params['to'].toUpperCase();
      return this.$element().append(`<h1>hi ${to}</h1>`);
    });
  });

  $(function() {
    return app.run("#/");
  });

}).call(this);
